# Generated by Django 3.2 on 2023-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='tally',
            field=models.IntegerField(default=0),
        ),
    ]
