# Generated by Django 4.1.7 on 2023-03-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '__first__'),
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(max_length=50, verbose_name='Activity: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='estimated_hours',
            field=models.FloatField(max_length=50, verbose_name='Estimated Hours: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_datetime',
            field=models.DateTimeField(max_length=50, verbose_name='Date and Time: '),
        ),
    ]
